version: '3'
services:
  db:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: semantic-server
    volumes:
      - ~/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data

  semantic-server:
    build: ./semanticserver
    image: semantic-server
    container_name: semantic-server
    ports:
      - "5002:8080"
    depends_on:
      - db


